CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "full_name" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "datasets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar NOT NULL,
  "description" text,
  "file_path" text NOT NULL,
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "models" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar NOT NULL,
  "description" text,
  "model_type" varchar,
  "file_path" text NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "predictions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "dataset_id" int,
  "model_id" int,
  "result_file_path" text,
  "status" varchar DEFAULT ('completed'),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action" text,
  "details" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "datasets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "models" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("dataset_id") REFERENCES "datasets" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("model_id") REFERENCES "models" ("id");

ALTER TABLE "logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
