-- 1. Users
CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "full_name" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 2. Projects (وابسته به users)
CREATE TABLE IF NOT EXISTS "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" varchar NOT NULL,
  "description" text,
  "visibility" varchar DEFAULT 'private', -- private | team | public
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 3. Datasets (وابسته به users)
CREATE TABLE IF NOT EXISTS "datasets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int REFERENCES "users" ("id"),
  "name" varchar NOT NULL,
  "description" text,
  "content" BYTEA NOT NULL,
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 4. Models (وابسته به users)
CREATE TABLE IF NOT EXISTS "models" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int REFERENCES "users" ("id"),
  "name" varchar NOT NULL,
  "description" text,
  "model_type" varchar,
  "file_path" text NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 5. Predictions (از اول project_id رو داریم)
CREATE TABLE IF NOT EXISTS "predictions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int REFERENCES "users" ("id"),
  "dataset_id" int REFERENCES "datasets" ("id"),
  "model_id" int REFERENCES "models" ("id"),
  "project_id" INT REFERENCES "projects"("id") ON DELETE CASCADE,
  "result_file_path" text,
  "status" varchar DEFAULT ('completed'),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 6. Logs (از اول project_id رو داریم)
CREATE TABLE IF NOT EXISTS "logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int REFERENCES "users" ("id"),
  "project_id" INT REFERENCES "projects"("id") ON DELETE SET NULL,
  "action" text,
  "details" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- 7. Project-Datasets (ارتباط N:N)
CREATE TABLE IF NOT EXISTS "project_datasets" (
  "project_id" INT NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "dataset_id" INT NOT NULL REFERENCES "datasets"("id") ON DELETE CASCADE,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("project_id","dataset_id")
);

-- 8. Project-Models (ارتباط N:N)
CREATE TABLE IF NOT EXISTS "project_models" (
  "project_id" INT NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "model_id" INT NOT NULL REFERENCES "models"("id") ON DELETE CASCADE,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("project_id","model_id")
);


-- 9. ایندکس‌ها
CREATE INDEX ON "project_datasets" ("project_id");
CREATE INDEX ON "project_models" ("project_id");
CREATE INDEX ON "predictions" ("project_id","created_at");
CREATE INDEX ON "logs" ("project_id","created_at");
