CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "full_name" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "datasets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar NOT NULL,
  "description" text,
  "file_path" text NOT NULL,
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "models" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar NOT NULL,
  "description" text,
  "model_type" varchar,
  "file_path" text NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "predictions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "dataset_id" int,
  "model_id" int,
  "result_file_path" text,
  "status" varchar DEFAULT ('completed'),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action" text,
  "details" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" varchar NOT NULL,
  "description" text,
  "visibility" varchar DEFAULT 'private', -- optional: 'private' | 'team' | 'public'
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "project_datasets" (
  "project_id" INT NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "dataset_id" INT NOT NULL REFERENCES "datasets"("id") ON DELETE CASCADE,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("project_id","dataset_id")
);

CREATE TABLE "project_models" (
  "project_id" INT NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "model_id" INT NOT NULL REFERENCES "models"("id") ON DELETE CASCADE,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("project_id","model_id")
);

ALTER TABLE "datasets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "models" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("dataset_id") REFERENCES "datasets" ("id");

ALTER TABLE "predictions" ADD FOREIGN KEY ("model_id") REFERENCES "models" ("id");

ALTER TABLE "logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "predictions" ADD COLUMN "project_id" INT;

ALTER TABLE "predictions" ADD CONSTRAINT "predictions_project_fk"
  FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE;

ALTER TABLE "logs" ADD COLUMN "project_id" INT;

ALTER TABLE "logs" ADD CONSTRAINT "logs_project_fk"
  FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE SET NULL;

CREATE INDEX ON "project_datasets" ("project_id");
CREATE INDEX ON "project_models" ("project_id");
CREATE INDEX ON "predictions" ("project_id","created_at");
CREATE INDEX ON "logs" ("project_id","created_at");

