// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dataset struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	FilePath    string           `json:"file_path"`
	UploadedAt  pgtype.Timestamp `json:"uploaded_at"`
}

type Log struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	ProjectID pgtype.Int4      `json:"project_id"`
	Action    pgtype.Text      `json:"action"`
	Details   pgtype.Text      `json:"details"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Model struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ModelType   pgtype.Text      `json:"model_type"`
	FilePath    string           `json:"file_path"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Prediction struct {
	ID             int32            `json:"id"`
	UserID         pgtype.Int4      `json:"user_id"`
	DatasetID      pgtype.Int4      `json:"dataset_id"`
	ModelID        pgtype.Int4      `json:"model_id"`
	ProjectID      pgtype.Int4      `json:"project_id"`
	ResultFilePath pgtype.Text      `json:"result_file_path"`
	Status         pgtype.Text      `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Project struct {
	ID          int32            `json:"id"`
	OwnerUserID int32            `json:"owner_user_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Visibility  pgtype.Text      `json:"visibility"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ProjectDataset struct {
	ProjectID int32            `json:"project_id"`
	DatasetID int32            `json:"dataset_id"`
	AddedAt   pgtype.Timestamp `json:"added_at"`
}

type ProjectModel struct {
	ProjectID int32            `json:"project_id"`
	ModelID   int32            `json:"model_id"`
	AddedAt   pgtype.Timestamp `json:"added_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	FullName     pgtype.Text      `json:"full_name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
